In [55]:
from scipy.io import arff
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [56]:
path = "./datasets_kaggle/breast-cancer/"
train_data = pd.read_csv("%sbreast-cancer-diagnostic.shuf.lrn.csv" % path)
competition_data = pd.read_csv("%sbreast-cancer-diagnostic.shuf.tes.csv" % path)

train_data.replace(['NONE', '?', '', 'None', b''], pd.NA, inplace=True)
competition_data.replace(['NONE', '?', '', 'None', b''], pd.NA, inplace=True)

train_data.drop(columns=['ID'], inplace=True)
competition_data.drop(columns=['ID'], inplace=True)

In [57]:
train_data

class  radiusMean   textureMean   perimeterMean   areaMean  \
0     True       13.96         17.05           91.43      602.4   
1     True       11.42         20.38           77.58      386.1   
2     True       21.37         15.10          141.30     1386.0   
3     True       18.22         18.87          118.70     1027.0   
4    False       15.71         13.93          102.00      761.7   
..     ...         ...           ...             ...        ...   
280  False       14.53         19.34           94.25      659.7   
281  False       13.49         22.30           86.91      561.0   
282  False       10.60         18.95           69.28      346.4   
283  False       13.59         21.84           87.16      561.0   
284  False       12.23         19.56           78.54      461.0   

      smoothnessMean   compactnessMean   concavityMean   concavePointsMean  \
0            0.10960           0.12790         0.09789             0.05246   
1            0.14250           0.28390         0.24140             0.10520   
2            0.10010           0.15150         0.19320             0.12550   
3            0.09746           0.11170         0.11300             0.07950   
4            0.09462           0.09462         0.07135             0.05933   
..               ...               ...             ...                 ...   
280          0.08388           0.07800         0.08817             0.02925   
281          0.08752           0.07698         0.04751             0.03384   
282          0.09688           0.11470         0.06387             0.02642   
283          0.07956           0.08259         0.04072             0.02142   
284          0.09586           0.08087         0.04187             0.04107   

      symmetryMean  ...   radiusWorst   textureWorst   perimeterWorst  \
0           0.1908  ...         16.39          22.07           108.10   
1           0.2597  ...         14.91          26.50            98.87   
2           0.1973  ...         22.69          21.84           152.10   
3           0.1807  ...         21.84          25.00           140.90   
4           0.1816  ...         17.50          19.25           114.30   
..             ...  ...           ...            ...              ...   
280         0.1473  ...         16.30          28.39           108.10   
281         0.1809  ...         15.15          31.82            99.00   
282         0.1922  ...         11.88          22.94            78.28   
283         0.1635  ...         14.80          30.04            97.66   
284         0.1979  ...         14.44          28.36            92.15   

      areaWorst   smoothnessWorst   compactnessWorst   concavityWorst  \
0         826.0            0.1512             0.3262           0.3209   
1         567.7            0.2098             0.8663           0.6869   
2        1535.0            0.1192             0.2840           0.4024   
3        1485.0            0.1434             0.2763           0.3853   
4         922.8            0.1223             0.1949           0.1709   
..          ...               ...                ...              ...   
280       830.5            0.1089             0.2649           0.3779   
281       698.8            0.1162             0.1711           0.2282   
282       424.8            0.1213             0.2515           0.1916   
283       661.5            0.1005             0.1730           0.1453   
284       638.4            0.1429             0.2042           0.1377   

      concavePointsWorst   symmetryWorst   fractalDimensionWorst  
0                0.13740          0.3068                 0.07957  
1                0.25750          0.6638                 0.17300  
2                0.19660          0.2730                 0.08666  
3                0.17760          0.2812                 0.08198  
4                0.13740          0.2723                 0.07071  
..                   ...             ...                     ...  
280              0.09594          0.2471

In [58]:
competition_data

radiusMean   textureMean   perimeterMean   areaMean   smoothnessMean  \
0         15.19         13.21           97.65      711.8          0.07963   
1         13.00         21.82           87.50      519.8          0.12730   
2         13.27         17.02           84.55      546.4          0.08445   
3         17.42         25.56          114.50      948.0          0.10060   
4         13.64         15.60           87.38      575.3          0.09423   
..          ...           ...             ...        ...              ...   
279       12.76         18.84           81.87      496.6          0.09676   
280       11.60         12.84           74.34      412.6          0.08983   
281       12.87         16.21           82.38      512.2          0.09425   
282       15.75         20.25          102.60      761.3          0.10250   
283       12.62         17.15           80.62      492.9          0.08583   

      compactnessMean   concavityMean   concavePointsMean   symmetryMean  \
0             0.06934         0.03393             0.02657         0.1721   
1             0.19320         0.18590             0.09353         0.2350   
2             0.04994         0.03554             0.02456         0.1496   
3             0.11460         0.16820             0.06597         0.1308   
4             0.06630         0.04705             0.03731         0.1717   
..                ...             ...                 ...            ...   
279           0.07952         0.02688             0.01781         0.1759   
280           0.07525         0.04196             0.03350         0.1620   
281           0.06219         0.03900             0.01615         0.2010   
282           0.12040         0.11470             0.06462         0.1935   
283           0.05430         0.02966             0.02272         0.1799   

      fractalDimensionMean  ...   radiusWorst   textureWorst   perimeterWorst  \
0                  0.05544  ...         16.20          15.73           104.50   
1                  0.07389  ...         15.49          30.73           106.20   
2                  0.05674  ...         15.14          23.60            98.84   
3                  0.05866  ...         18.07          28.07           120.40   
4                  0.05660  ...         14.85          19.05            94.11   
..                     ...  ...           ...            ...              ...   
279                0.06183  ...         13.75          25.99            87.82   
280                0.06582  ...         13.06          17.16            82.96   
281                0.05769  ...         13.90          23.64            89.27   
282                0.06303  ...         19.56          30.29           125.90   
283                0.05826  ...         14.34          22.15            91.62   

      areaWorst   smoothnessWorst   compactnessWorst   concavityWorst  \
0         819.1            0.1126             0.1737           0.1362   
1         739.3            0.1703             0.5401           0.5390   
2         708.8            0.1276             0.1311           0.1786   
3        1021.0            0.1243             0.1793           0.2803   
4         683.4            0.1278             0.1291           0.1533   
..          ...               ...                ...              ...   
279       579.7            0.1298             0.1839           0.1255   
280       512.5            0.1431             0.1851           0.1922   
281       597.5            0.1256             0.1808           0.1992   
282      1088.0            0.1552             0.4480           0.3976   
283       633.5            0.1225             0.1517           0.1887   

      concavePointsWorst   symmetryWorst   fractalDimensionWorst  
0                0.08178          0.2487                 0.06766  
1                0.20600          0.4378                 0.10720  
2                0.09678          0.2506                 0.07623  
3                0.10990          0.1603         

In [59]:
y = train_data[('class')] 
X = train_data.drop('class', axis=1)  # Features


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
# y_comp = competition_data['grade']  # Target variable does not exist for competition data
X_comp = competition_data
print(X_train.dtypes)

radiusMean                 float64
 textureMean               float64
 perimeterMean             float64
 areaMean                  float64
 smoothnessMean            float64
 compactnessMean           float64
 concavityMean             float64
 concavePointsMean         float64
 symmetryMean              float64
 fractalDimensionMean      float64
 radiusStdErr              float64
 textureStdErr             float64
 perimeterStdErr           float64
 areaStdErr                float64
 smoothnessStdErr          float64
 compactnessStdErr         float64
 concavityStdErr           float64
 concavePointsStdErr       float64
 symmetryStdErr            float64
 fractalDimensionStdErr    float64
 radiusWorst               float64
 textureWorst              float64
 perimeterWorst            float64
 areaWorst                 float64
 smoothnessWorst           float64
 compactnessWorst          float64
 concavityWorst            float64
 concavePointsWorst        float64
 symmetryWorst      

In [60]:
print("null values in train data: "+ str(X_train.isnull().sum().sum()))
print("null values in test data: "+ str(X_test.isnull().sum().sum()))
print("null values in competition data: "+ str(X_comp.isnull().sum().sum()))

null values in train data: 0
null values in test data: 0
null values in competition data: 0


In [61]:
pipeline = Pipeline([
    ('scaler', MinMaxScaler()),
    #('scaler', StandardScaler())
])

# Preprocess training data
X_train = pipeline.fit_transform(X_train)
X_test = pipeline.transform(X_test)
X_comp = pipeline.transform(X_comp)

In [62]:
# Encode target variable
label_encoder = LabelEncoder()

y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

In [63]:
clf = MLPClassifier(solver='adam', activation='relu', alpha=1e-4, hidden_layer_sizes=(25, 25, 25), random_state=7895, max_iter=3000, verbose=True, tol=5e-5)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1 Score:", f1)

# confusion matrix
confusion_matrix(y_test, y_pred)

Iteration 1, loss = 0.64648080
Iteration 2, loss = 0.64149572
Iteration 3, loss = 0.63653251
Iteration 4, loss = 0.63161473
Iteration 5, loss = 0.62672363
Iteration 6, loss = 0.62177210
Iteration 7, loss = 0.61687545
Iteration 8, loss = 0.61203508
Iteration 9, loss = 0.60716258
Iteration 10, loss = 0.60221431
Iteration 11, loss = 0.59726910
Iteration 12, loss = 0.59220913
Iteration 13, loss = 0.58712131
Iteration 14, loss = 0.58204504
Iteration 15, loss = 0.57697545
Iteration 16, loss = 0.57190003
Iteration 17, loss = 0.56695081
Iteration 18, loss = 0.56204283
Iteration 19, loss = 0.55706619
Iteration 20, loss = 0.55204320
Iteration 21, loss = 0.54688233
Iteration 22, loss = 0.54152998
Iteration 23, loss = 0.53605269
Iteration 24, loss = 0.53046421
Iteration 25, loss = 0.52479941
Iteration 26, loss = 0.51910428
Iteration 27, loss = 0.51330793
Iteration 28, loss = 0.50738830
Iteration 29, loss = 0.50133878
Iteration 30, loss = 0.49518189
Iteration 31, loss = 0.48889791
Iteration 32, los

array([[88,  2],
       [ 2, 51]])

In [64]:
confusion_matrix(y_test, y_pred)
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

rf_classifier.fit(X_train, y_train)
y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1 Score:", f1)

# confusion matrix
confusion_matrix(y_test, y_pred)

Accuracy: 0.965034965034965
Recall: 0.965034965034965
Precision: 0.9649965419196188
F1 Score: 0.9649650533628434


array([[88,  2],
       [ 3, 50]])

In [65]:
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1 Score:", f1)

# confusion matrix
confusion_matrix(y_test, y_pred)

Accuracy: 0.972027972027972
Recall: 0.972027972027972
Precision: 0.9722098021330758
F1 Score: 0.9719127026819333


array([[89,  1],
       [ 3, 50]])